### PR TITLE
Save Crash Reports to File

### LINKED ISSUE #93: Add a way to save crash reports to file
JUCE has built in ways of doing things on-crash. It would help diagnose issues to add a proper crash handler to our VT.

### PR DESCRIPTION
**Pull request by ad3154**
This adds saving of a basic stack backtrace when the application crashes, that way when people send us logs, we also get any relevant crashes.

Closes #93 

Tested by introducing intentional crashes and verified they ended up in a file at the intended location.

### CODE REVIEW

File: include/Main.hpp [hunk 1]
```diff
@@ -83,6 +85,24 @@ class AgISOVirtualTerminalApplication : public juce::JUCEApplication
...
 	}
 
+	static void onCrash(void *)
+	{
+		auto stackTrace = SystemStats::getStackBacktrace();
+		auto appDataDir = File(File::getSpecialLocation(File::userApplicationDataDirectory).getFullPathName() +
+		                       File::getSeparatorString() +
+		                       "Open-Agriculture" +
+		                       File::getSeparatorString());
+		String timestamp(static_cast<uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count()));
```
Comment (martonmiklos) [inline include/Main.hpp:95]: Would not be better to add "human" datetime to the filename? CAN logs have the same format, it would be easier to match them with eyes I think.

**Review by martonmiklos — COMMENTED** [review]
LGTM

File: include/Main.hpp (hunk 1 above)
Comment (ad3154) [reply include/Main.hpp:95]: Sure, I can use the same timestamp format as the logs. I will update it

**Review by martonmiklos — APPROVED** [review]
LGTM
